Controllers/ListingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SA_Auction.Data;
using SA_Auction.Data.Services;
using SA_Auction.Models;

namespace SA_Auction.Controllers
{

    public class ListingsController : Controller
    {

        private readonly IListingService _listingsService;
        private readonly IBidsService _bidsService;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly ICommentsService _commentsService;

        public ListingsController(IListingService listingsService, IBidsService bidsService,IWebHostEnvironment webHostEnvironment, ICommentsService commentsService)
        {
            _listingsService = listingsService;
            _webHostEnvironment = webHostEnvironment;
            _bidsService = bidsService;
            _commentsService = commentsService;

        }

        // GET: Listings
        public async Task<IActionResult> Index(int? pageNumber, string searchString)
        {
            var applicationDbContext = _listingsService.GetAll();
            int pageSize = 3;
            if (!string.IsNullOrEmpty(searchString))
            {
                applicationDbContext = applicationDbContext.Where(a => a.Title.Contains(searchString));
                return View(await PaginatedList<Listing>.CreateAsync(applicationDbContext.Where(l => l.IsSold == false).AsNoTracking(), pageNumber ?? 1, pageSize));

            }

            return View(await PaginatedList<Listing>.CreateAsync(applicationDbContext.Where(l => l.IsSold == false).AsNoTracking(), pageNumber ?? 1, pageSize));
        }
        public async Task<IActionResult> MyListings(int? pageNumber)
        {
            var applicationDbContext = _listingsService.GetAll();
            int pageSize = 3;

            return View("Index", await PaginatedList<Listing>.CreateAsync(applicationDbContext.Where(l => l.IdentityUserId == User.FindFirstValue(ClaimTypes.NameIdentifier)).AsNoTracking(), pageNumber ?? 1, pageSize));
        }
        public async Task<IActionResult> MyBids(int? pageNumber)
        {
            var applicationDbContext = _bidsService.GetAll();
            int pageSize = 3;

            return View(await PaginatedList<Bid>.CreateAsync(applicationDbContext.Where(l => l.IdentityUserId == User.FindFirstValue(ClaimTypes.NameIdentifier)).AsNoTracking(), pageNumber ?? 1, pageSize));
        }

        // GET: Listings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var listing = await _listingsService.GetById(id);

            if (listing == null)
            {
                return NotFound();
            }

            return View(listing);
        }

        // GET: Listings/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Listings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ListingVM listing)
        {
            if (listing.Image != null)
            {
                string uploadDir = Path.Combine(_webHostEnvironment.WebRootPath, "Images");
                string fileName = listing.Image.FileName;
                string filePath = Path.Combine(uploadDir, fileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    listing.Image.CopyTo(fileStream);
                }

                var listObj = new Listing
                {
                    Title = listing.Title,
                    Description = listing.Description,
                    Price = listing.Price,
                    IdentityUserId = listing.IdentityUserId,
                    ImagePath = fileName,
                };
                await _listingsService.Add(listObj);
                return RedirectToAction("Index");
            }
            return View(listing);
        }
        [HttpPost]
        public async Task<ActionResult> AddBid([Bind("Id, Price, ListingId, IdentityUserId")] Bid bid)
        {
            if (ModelState.IsValid)
            {
                await _bidsService.Add(bid);
            }
            var listing = await _listingsService.GetById(bid.ListingId);
            listing.Price = bid.Price;
            await _listingsService.SaveChanges();

            return View("Details", listing);
        }
        public async Task<ActionResult> CloseBidding(int id)
        {
            var listing = await _listingsService.GetById(id);
            listing.IsSold = true;
            await _listingsService.SaveChanges();
            return View("Details", listing);
        }

        [HttpPost]
        public async Task<ActionResult> AddComment([Bind("Id, Content, ListingId, IdentityUserId")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                await _commentsService.Add(comment);
            }
            var listing = await _listingsService.GetById(comment.ListingId);
            return View("Details", listing);
        }

        public async Task<IActionResult> CartViewAsync()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var wonBids = await _bidsService.GetWonBidsByUserIdAsync(userId);
            return View(wonBids);
        }


        // [httppost]
        //public async task<actionresult> addcomment([bind("id, content, listingid, identityuserid")] comment comment)
        //{
        //    if (modelstate.isvalid)
        //    {
        //        await _commentsservice.add(comment);
        //    }
        //    var listing = await _listingsservice.getbyid(comment.listingid);
        //    return view("details", listing);
        //}

        //// GET: Listings/Edit/5
        //public async Task<IActionResult> Edit(int? id)
        //{
        //    if (id == null || _context.Listings == null)
        //    {
        //        return NotFound();
        //    }

        //    var listing = await _context.Listings.FindAsync(id);
        //    if (listing == null)
        //    {
        //        return NotFound();
        //    }
        //    ViewData["IdentityUserId"] = new SelectList(_context.Users, "Id", "Id", listing.IdentityUserId);
        //    return View(listing);
        //}

        //// POST: Listings/Edit/5
        //// To protect from overposting attacks, enable the specific properties you want to bind to.
        //// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,Price,ImagePath,IsSold,IdentityUserId")] Listing listing)
        //{
        //    if (id != listing.Id)
        //    {
        //        return NotFound();
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            _context.Update(listing);
        //            await _context.SaveChangesAsync();
        //        }
        //        catch (DbUpdateConcurrencyException)
        //        {
        //            if (!ListingExists(listing.Id))
        //            {
        //                return NotFound();
        //            }
        //            else
        //            {
        //                throw;
        //            }
        //        }
        //        return RedirectToAction(nameof(Index));
        //    }
        //    ViewData["IdentityUserId"] = new SelectList(_context.Users, "Id", "Id", listing.IdentityUserId);
        //    return View(listing);
        //}

        //// GET: Listings/Delete/5
        //public async Task<IActionResult> Delete(int? id)
        //{
        //    if (id == null || _context.Listings == null)
        //    {
        //        return NotFound();
        //    }

        //    var listing = await _context.Listings
        //        .Include(l => l.User)
        //        .FirstOrDefaultAsync(m => m.Id == id);
        //    if (listing == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(listing);
        //}

        //// POST: Listings/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> DeleteConfirmed(int id)
        //{
        //    if (_context.Listings == null)
        //    {
        //        return Problem("Entity set 'ApplicationDbContext.Listings'  is null.");
        //    }
        //    var listing = await _context.Listings.FindAsync(id);
        //    if (listing != null)
        //    {
        //        _context.Listings.Remove(listing);
        //    }

        //    await _context.SaveChangesAsync();
        //    return RedirectToAction(nameof(Index));
        //}

        //private bool ListingExists(int id)
        //{
        //  return (_context.Listings?.Any(e => e.Id == id)).GetValueOrDefault();
        //
        //}
    }
}

    

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Auctions</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Auctions.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
</head>
<body>
    <header class="header" data-header>

        <div class="overlay" data-overlay></div>

        <div class="header-top">
            <div class="container">

                <ul class="header-top-list">

                    <li>
                        <a href="mailto:info@homeverse.com" class="header-top-link">
                            <img src="/Images/mail.png" width="26" height="25">

                            <span>info@homeverse.com</span>
                        </a>
                    </li>

                    <li>
                        <a href="#" class="header-top-link">
                            &nbsp; &nbsp; &nbsp;
                            <img src="/Images/location1.png" width="25">

                            <address>
                                15,Colombo
                            </address>
                        </a>
                    </li>

                </ul>

                <div class="wrapper">
                    <ul class="header-top-social-list">

                        <li>
                            <a href="#" class="header-top-social-link">
                                <ion-icon name="logo-facebook"></ion-icon>
                            </a>
                        </li>

                        <li>
                            <a href="#" class="header-top-social-link">
                                <ion-icon name="logo-twitter"></ion-icon>
                            </a>
                        </li>

                        <li>
                            <a href="#" class="header-top-social-link">
                                <ion-icon name="logo-instagram"></ion-icon>
                            </a>
                        </li>

                        <li>
                            <a href="#" class="header-top-social-link">
                                <ion-icon name="logo-pinterest"></ion-icon>
                            </a>
                        </li>

                    </ul>

                </div>

            </div>
        </div>

        <div class="header-bottom">
            <div class="container">

                <a href="#" class="logo">
                    <img src="/Images/logoo-auction.jpg" alt="Homeverse logo">
                </a>
                <nav class="navbar" data-navbar>

                    <div class="navbar-top">

                        <a href="#" class="logo">
                            <img src="/Images/logoo-auction.jpg" alt="Homeverse logo">
                        </a>

                        <button class="nav-close-btn" data-nav-close-btn aria-label="Close Menu">
                            <ion-icon name="close-outline"></ion-icon>
                        </button>

                    </div>

                    <div class="navbar-bottom">
                        <ul class="navbar-list">
                            <li>
                                <a class="navbar-link" data-nav-link asp-area="" asp-controller="Home" asp-action="Index"> Home</a>
                            </li>                           

                            <li>
                                <a  class="navbar-link" data-nav-link asp-area="" asp-controller="Listings" asp-action="Index"><i class="fa fa-solid fa-house"></i> Active Listings</a>
                            </li>

                           
                        </ul>
                    </div>
                   

                </nav>
                <div class="header-bottom-actions">

                    <form asp-controller="Listings" asp-action="Index" method="get" class="d-flex align-items-center">
                        <i class="fa fa-solid fa-search"></i>&nbsp;&nbsp;
                        <input type="text" name="searchString" class="form-control" placeholder="Search" />
                        <button class="header-bottom-actions-btn" aria-label="Search">
                            <span>Search</span>
                        </button>
                    </form>

                     @if (User.Identity.IsAuthenticated)
                     {
                        <button class="header-bottom-actions-btn" onclick="location.href='@Url.Page("/Account/Manage/Index", new { area = "Identity" })'" title="Manage" aria-label="Profile">
                            <ion-icon name="person-outline"></ion-icon>
                            <span>Profile</span>
                        </button>


                        <button class="header-bottom-actions-btn" onclick="location.href='@Url.Action("CartView", "Listings")'" aria-label="CartView">
                            <ion-icon name="cart-outline"></ion-icon>
                            <span>Cart</span>
                        </button>


                              
                     }
                    <partial name="_LoginPartial" />
                </div>
                <button class="header-bottom-actions-btn" data-nav-open-btn aria-label="Open Menu">
                    <ion-icon name="menu-outline"></ion-icon>

                    <span>Menu</span>
                </button>
            </div>                 
           
    </header>
    <main>
        <article>
            <div class="containerNav">
                <nav>
                    <ul>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li>
                                <a class="navbar-link " data-nav-link asp-area="" asp-controller="Listings" asp-action="Create"><i class="fa fa-solid fa-plus"></i> Create Listing</a>
                            </li>
                            <li>
                                <a class="navbar-link " data-nav-link asp-area="" asp-controller="Listings" asp-action="MyListings"><i class="fa fa-solid fa-newspaper"></i> My Listings</a>
                            </li>
                            <li>
                                <a class="navbar-link " data-nav-link asp-area="" asp-controller="Listings" asp-action="MyBids"><i class="fa fa-solid fa-sack-dollar"></i> My Bids</a>
                            </li>
                        }
                    </ul>
                </nav>
            </div>
            @RenderBody()
        </article>
    </main>   

    <footer class="footer">

        <div class="footer-top">
            <div class="container">

                <div class="footer-brand">

                    <a href="#" class="logo">
                        <img src="/Images/logoo-auction.jpg" alt="Homeverse logo">
                    </a>

                    <p class="section-text">
                        Lorem Ipsum is simply dummy text of the and typesetting industry. Lorem Ipsum is dummy text of the printing.
                    </p>

                    <ul class="contact-list">

                        <li>
                            <a href="#" class="contact-link">
                                <ion-icon name="location-outline"></ion-icon>

                                <address>
                                    Colombo, Srilanka.&nbsp;
                                </address>
                            </a>
                        </li>

                        <li>
                            <a href="tel:+0123456789" class="contact-link">
                                <ion-icon name="call-outline"></ion-icon>

                                <span>+0123-456789</span>
                            </a>
                        </li>

                        <li>
                            <a href="mailto:contact@homeverse.com" class="contact-link">
                                <ion-icon name="mail-outline"></ion-icon>

                                <span>contact@homeverse.com</span>
                            </a>
                        </li>

                    </ul>

                    <ul class="social-list">

                        <li>
                            <a href="#" class="social-link">
                                <ion-icon name="logo-facebook"></ion-icon>
                            </a>
                        </li>

                        <li>
                            <a href="#" class="social-link">
                                <ion-icon name="logo-twitter"></ion-icon>
                            </a>
                        </li>

                        <li>
                            <a href="#" class="social-link">
                                <ion-icon name="logo-linkedin"></ion-icon>
                            </a>
                        </li>

                        <li>
                            <a href="#" class="social-link">
                                <ion-icon name="logo-youtube"></ion-icon>
                            </a>
                        </li>

                    </ul>

                </div>

                <div class="footer-link-box">

                    <ul class="footer-list">

                        <li>
                            <p class="footer-list-title">Company</p>
                        </li>

                        <li>
                            <a href="#" class="footer-link">About</a>
                        </li>

                        <li>
                            <a href="#" class="footer-link">Blog</a>
                        </li>

                        <li>
                            <a href="#" class="footer-link">All Products</a>
                        </li>

                        <li>
                            <a href="#" class="footer-link">Locations Map</a>
                        </li>

                        <li>
                            <a href="#" class="footer-link">FAQ</a>
                        </li>

                        <li>
                            <a href="#" class="footer-link">Contact us</a>
                        </li>

                    </ul>

                    <ul class="footer-list">

                        <li>
                            <p class="footer-list-title">Services</p>
                        </li>

                        <li>
                            <a href="#" class="footer-link">Order tracking</a>
                        </li>

                        <li>
                            <a href="#" class="footer-link">Wish List</a>
                        </li>

                        <li>
                            <a href="#" class="footer-link">Login</a>
                        </li>

                        <li>
                            <a href="#" class="footer-link">My account</a>
                        </li>

                        <li>
                            <a href="#" class="footer-link">Terms & Conditions</a>
                        </li>

                        <li>
                            <a href="#" class="footer-link">Promotional Offers</a>
                        </li>

                    </ul>

                    <ul class="footer-list">

                        <li>
                            <p class="footer-list-title">Customer Care</p>
                        </li>

                        <li>
                            <a href="#" class="footer-link">Login</a>
                        </li>

                        <li>
                            <a href="#" class="footer-link">My account</a>
                        </li>

                        <li>
                            <a href="#" class="footer-link">Wish List</a>
                        </li>

                        <li>
                            <a href="#" class="footer-link">Order tracking</a>
                        </li>

                        <li>
                            <a href="#" class="footer-link">FAQ</a>
                        </li>

                        <li>
                            <a href="#" class="footer-link">Contact us</a>
                        </li>

                    </ul>

                </div>

            </div>
        </div>

        <div class="footer-bottom">
            <div class="container">

                <p class="copyright">
                    &copy; 2024 <a href="#">Artistic Web Work</a>. All Rights Reserved
                </p>

            </div>
        </div>

    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
   
    <!-- ion icon -->
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>